version: '3.7'
services:
  backend:
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    build:
      context: .
      dockerfile: Dockerfile
    container_name: daily-emotion-backend
    ports:
      - "8080:8080"
    env_file:
      - ./env/common.env
      - ./env/dev.env
    depends_on:
      - mariadb
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: daily-emotion-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    container_name: daily-emotion-mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: daily_emotion
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app-network