version: '3.7'

services:
  backend:
    environment:
      - SPRING_PROFILES_ACTIVE=prod # application-prod.yml을 자동으로 적용
    build:
      context: .
      dockerfile: Dockerfile
    container_name: daily-emotion-backend
    ports:
      - "8080:8080"
    env_file:
      - ./env/common.env
      - ./env/prod.env
    networks:
      - app-network
    restart: no
  redis:
    image: redis:latest
    container_name: daily-emotion-redis
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: unless-stopped
  mariadb:
    image: mariadb:latest
    container_name: daily-emotion-mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: 1234   # root 비밀번호 설정
      MARIADB_DATABASE: daily_emotion_db  # 기본 데이터베이스 생성
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d  # 초기화 스크립트 경로 마운트
    networks:
      - app-network
    restart: unless-stopped

volumes:
  redis-data:
    name: daily-emotion-redis-data
  mariadb-data:
    name: daily-emotion-data

networks:
  app-network:
    name: daily-emotion-network
    driver: bridge