version: '3.7'
services:
  backend:
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE},oauth
      - SPRING_DATASOURCE_URL=jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: daily-emotion-backend
    ports:
      - "8080:8080"
    volumes:
      - ./gcp-key.json:/app/gcp-key.json
    env_file:
      - .env  # <-- 여기 "-" 추가해서 올바르게 설정
    depends_on:
      - mariadb
      - redis
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: daily-emotion-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    container_name: daily-emotion-mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app-network
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  mariadb-data:
