spring:
  config:
    import:
      - optional:file:./env/common.env[common]
      - optional:file:./env/prod.env[prod]

  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  # 데이터베이스 설정
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}  # 운영 환경 변수로 관리
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}