spring:
  application:
    name: daily-emotion
  # 데이터베이스 설정
  datasource:
    url: jdbc:mariadb://daily-emotion-mariadb:3306/daily_emotion
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

# 디버그 설정 추가
debug: true
logging:
  level:
    org.springframework.boot.context.config: TRACE