spring:
  config:
    activate:
      on-profile: prod

  # 운영 환경 MariaDB 설정
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}

  # Redis (운영 환경)
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: ${REDIS_TIMEOUT}

# 로깅 설정 (운영용)
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.dailyemotion: debug
