spring:
  config:
    import:
      - optional:file:./env/common.env[common]
      - optional:file:./env/dev.env[prod]
      - optional:classpath:application-oauth.yml
  application:
    name: daily-emotion
  profiles:
    group:
      dev:
        - oauth
      prod:
        - oauth

  datasource:
    url: jdbc:mariadb://mariadb:3306/daily_emotion
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET}
  accessExpiration: ${JWT_ACCESS_EXPIRATION}
  refreshExpiration: ${JWT_REFRESH_EXPIRATION}

springdoc:
  swagger-ui:
    operations-sorter: get-post-put-delete
    tagsSorter: alpha

logging:
  level:
    org.springframework.security: DEBUG