spring:
  config:
    import:
      - optional:file:./env/common.env[common]
      - optional:file:./env/dev.env[dev]

  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  # 데이터베이스 설정
  datasource:
    url: jdbc:mariadb://daily-emotion-mariadb:3306/daily_emotion
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}